//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookListItems
    {
        public int ItemId { get; set; }
        public int UserId { get; set; }
        public int BookId { get; set; }
        public string ListName { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
    }
}
